name: absinthe_socket
description: A GraphQL subscription client for Absinthe sockets (cloned for Postagraph).
version: 0.0.4
author: Josh Adams <josh@smoothterminal.com>
homepage: http://github.com/dailydrip/absinthe_socket

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Talk to phoenix channels
  phoenix_wings: 
    git:
      url: https://github.com/redDwarf03/phoenix_wings.git
      ref: master
